<?php
// Generado por tools/generate_catalog.py — MinasLab catálogo curricular.

namespace mod_minaslab\local;

defined('MOODLE_INTERNAL') || die();

final class activity_catalog_data {

    /** @return array<string, array<string, mixed>> */
    public static function entries(): array {
        return [
            's1_algebra_a' => [
                'semester' => 1,
                'subject_slug' => 'algebra',
                'subject_name' => 'Álgebra',
                'title' => 'Galería 3D: matrices para programar cargas en voladura (sistemas 2×2)',
                'archetype' => 'tunnel_3d',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Álgebra: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: tunnel_3d.',
            ],
            's1_algebra_b' => [
                'semester' => 1,
                'subject_slug' => 'algebra',
                'subject_name' => 'Álgebra',
                'title' => 'Taller: trigonometría del barreno respecto al plano de banco',
                'archetype' => 'math_mine',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Álgebra: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: math_mine.',
            ],
            's1_algebra_c' => [
                'semester' => 1,
                'subject_slug' => 'algebra',
                'subject_name' => 'Álgebra',
                'title' => 'Simulación numérica: complejos y fasores en arranque de motor de ventilador',
                'archetype' => 'math_mine',
                'profile' => [4],
                'summary' => 'Actividad práctica para Álgebra: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: math_mine.',
            ],
            's1_bases_ops_a' => [
                'semester' => 1,
                'subject_slug' => 'bases_ops',
                'subject_name' => 'Bases de las Operaciones Mineras',
                'title' => 'Túnel de acceso: aplicar DS 132 y señalética en desarrollo subterráneo',
                'archetype' => 'tunnel_3d',
                'profile' => [1, 3],
                'summary' => 'Actividad práctica para Bases de las Operaciones Mineras: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C3). Escenario: tunnel_3d.',
            ],
            's1_bases_ops_b' => [
                'semester' => 1,
                'subject_slug' => 'bases_ops',
                'subject_name' => 'Bases de las Operaciones Mineras',
                'title' => 'Rajo abierto: ciclo perforación–carguío–transporte y botadero',
                'archetype' => 'pit_3d',
                'pit_scene' => 'cycle',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Bases de las Operaciones Mineras: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: pit_3d.',
            ],
            's1_bases_ops_c' => [
                'semester' => 1,
                'subject_slug' => 'bases_ops',
                'subject_name' => 'Bases de las Operaciones Mineras',
                'title' => 'Escena integrada: cierre de faena y aspectos del plan de cierre',
                'archetype' => 'pit_3d',
                'profile' => [2, 3, 6],
                'summary' => 'Actividad práctica para Bases de las Operaciones Mineras: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C3, C6). Escenario: pit_3d.',
            ],
            's1_prep_min_a' => [
                'semester' => 1,
                'subject_slug' => 'prep_min',
                'subject_name' => 'Elementos de Preparación de Minerales',
                'title' => 'Flujo en planta: chancado, cribado y concentración (diagrama interactivo)',
                'archetype' => 'flow_process',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Elementos de Preparación de Minerales: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: flow_process.',
            ],
            's1_prep_min_b' => [
                'semester' => 1,
                'subject_slug' => 'prep_min',
                'subject_name' => 'Elementos de Preparación de Minerales',
                'title' => 'Laboratorio: hidrometalurgia vs pirometalurgia en mena de ejemplo',
                'archetype' => 'flow_process',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Elementos de Preparación de Minerales: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: flow_process.',
            ],
            's1_prep_min_c' => [
                'semester' => 1,
                'subject_slug' => 'prep_min',
                'subject_name' => 'Elementos de Preparación de Minerales',
                'title' => 'Balance conceptual: recuperación y ley de concentrado',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Elementos de Preparación de Minerales: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's1_ingles_a' => [
                'semester' => 1,
                'subject_slug' => 'ingles',
                'subject_name' => 'Inglés Técnico',
                'title' => 'Briefing en frente de trabajo: vocabulario de EPI y herramientas (HUD minero)',
                'archetype' => 'english_mine',
                'profile' => [5],
                'summary' => 'Actividad práctica para Inglés Técnico: vinculada al programa de asignatura y al perfil de egreso (competencias C5). Escenario: english_mine.',
            ],
            's1_ingles_b' => [
                'semester' => 1,
                'subject_slug' => 'ingles',
                'subject_name' => 'Inglés Técnico',
                'title' => 'Lectura de manual: especificaciones de bomba y válvula en inglés',
                'archetype' => 'english_mine',
                'profile' => [5],
                'summary' => 'Actividad práctica para Inglés Técnico: vinculada al programa de asignatura y al perfil de egreso (competencias C5). Escenario: english_mine.',
            ],
            's1_ingles_c' => [
                'semester' => 1,
                'subject_slug' => 'ingles',
                'subject_name' => 'Inglés Técnico',
                'title' => 'Comunicación por radio: frases de corto alcance en faena simulada',
                'archetype' => 'english_mine',
                'profile' => [5],
                'summary' => 'Actividad práctica para Inglés Técnico: vinculada al programa de asignatura y al perfil de egreso (competencias C5). Escenario: english_mine.',
            ],
            's1_prev_riesgos_a' => [
                'semester' => 1,
                'subject_slug' => 'prev_riesgos',
                'subject_name' => 'Prevención de Riesgos',
                'title' => 'Inspección en galería: identificar fuentes de riesgo y controles',
                'archetype' => 'safety_module',
                'profile' => [3, 6],
                'summary' => 'Actividad práctica para Prevención de Riesgos: vinculada al programa de asignatura y al perfil de egreso (competencias C3, C6). Escenario: safety_module.',
            ],
            's1_prev_riesgos_b' => [
                'semester' => 1,
                'subject_slug' => 'prev_riesgos',
                'subject_name' => 'Prevención de Riesgos',
                'title' => 'Plan de emergencia: simulacro de evacuación y puntos de encuentro',
                'archetype' => 'safety_module',
                'profile' => [3, 5],
                'summary' => 'Actividad práctica para Prevención de Riesgos: vinculada al programa de asignatura y al perfil de egreso (competencias C3, C5). Escenario: safety_module.',
            ],
            's1_prev_riesgos_c' => [
                'semester' => 1,
                'subject_slug' => 'prev_riesgos',
                'subject_name' => 'Prevención de Riesgos',
                'title' => 'Evaluación de riesgo en rajo: caída de roca y distancia de seguridad',
                'archetype' => 'safety_module',
                'profile' => [3],
                'summary' => 'Actividad práctica para Prevención de Riesgos: vinculada al programa de asignatura y al perfil de egreso (competencias C3). Escenario: safety_module.',
            ],
            's1_topo_planos_a' => [
                'semester' => 1,
                'subject_slug' => 'topo_planos',
                'subject_name' => 'Topografía e Interpretación de Planos',
                'title' => 'Mesa de planos: escalas, norte y lectura de galerías en planta',
                'archetype' => 'survey_field',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Topografía e Interpretación de Planos: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: survey_field.',
            ],
            's1_topo_planos_b' => [
                'semester' => 1,
                'subject_slug' => 'topo_planos',
                'subject_name' => 'Topografía e Interpretación de Planos',
                'title' => 'Replanteo: ángulos y distancias en túnel (polígono simplificado)',
                'archetype' => 'survey_field',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Topografía e Interpretación de Planos: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: survey_field.',
            ],
            's1_topo_planos_c' => [
                'semester' => 1,
                'subject_slug' => 'topo_planos',
                'subject_name' => 'Topografía e Interpretación de Planos',
                'title' => 'Sección transversal: correlacionar perfil con vista en planta',
                'archetype' => 'survey_field',
                'profile' => [4],
                'summary' => 'Actividad práctica para Topografía e Interpretación de Planos: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: survey_field.',
            ],
            's2_calculo_a' => [
                'semester' => 2,
                'subject_slug' => 'calculo',
                'subject_name' => 'Cálculo',
                'title' => 'Derivadas: tasa de cambio del tonelaje transportado en correa',
                'archetype' => 'math_mine',
                'profile' => [1, 2, 4],
                'summary' => 'Actividad práctica para Cálculo: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2, C4). Escenario: math_mine.',
            ],
            's2_calculo_b' => [
                'semester' => 2,
                'subject_slug' => 'calculo',
                'subject_name' => 'Cálculo',
                'title' => 'Integrales: acumulado de producción en turno (área bajo curva)',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Cálculo: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's2_calculo_c' => [
                'semester' => 2,
                'subject_slug' => 'calculo',
                'subject_name' => 'Cálculo',
                'title' => 'Optimización: punto de mínimo costo por tonelada (conceptual)',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Cálculo: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's2_fisica_sup_a' => [
                'semester' => 2,
                'subject_slug' => 'fisica_sup',
                'subject_name' => 'Física Superior',
                'title' => 'Ondas y vibración: riesgo de resonancia en estructura de soporte',
                'archetype' => 'math_mine',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Física Superior: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: math_mine.',
            ],
            's2_fisica_sup_b' => [
                'semester' => 2,
                'subject_slug' => 'fisica_sup',
                'subject_name' => 'Física Superior',
                'title' => 'Campo y circuito: potencia del motor de compresor (conceptual)',
                'archetype' => 'math_mine',
                'profile' => [4],
                'summary' => 'Actividad práctica para Física Superior: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: math_mine.',
            ],
            's2_fisica_sup_c' => [
                'semester' => 2,
                'subject_slug' => 'fisica_sup',
                'subject_name' => 'Física Superior',
                'title' => 'Energía: balance trabajo–energía en elevación de mineral',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Física Superior: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's2_geo_est_a' => [
                'semester' => 2,
                'subject_slug' => 'geo_est',
                'subject_name' => 'Geología Estructural y de Minas',
                'title' => 'Túnel de exploración: mapear pliegue y falla en el macizo',
                'archetype' => 'tunnel_3d',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Geología Estructural y de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: tunnel_3d.',
            ],
            's2_geo_est_b' => [
                'semester' => 2,
                'subject_slug' => 'geo_est',
                'subject_name' => 'Geología Estructural y de Minas',
                'title' => 'Pit: orientación de estructuras y control del talud',
                'archetype' => 'pit_3d',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Geología Estructural y de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: pit_3d.',
            ],
            's2_geo_est_c' => [
                'semester' => 2,
                'subject_slug' => 'geo_est',
                'subject_name' => 'Geología Estructural y de Minas',
                'title' => 'Corte geológico: correlacionar litología con geometría del yacimiento',
                'archetype' => 'pit_3d',
                'profile' => [4],
                'summary' => 'Actividad práctica para Geología Estructural y de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: pit_3d.',
            ],
            's2_prob_est_a' => [
                'semester' => 2,
                'subject_slug' => 'prob_est',
                'subject_name' => 'Probabilidad y Estadística',
                'title' => 'Distribución de leyes de sondaje: media e intervalo en bloque ficticio',
                'archetype' => 'math_mine',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Probabilidad y Estadística: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: math_mine.',
            ],
            's2_prob_est_b' => [
                'semester' => 2,
                'subject_slug' => 'prob_est',
                'subject_name' => 'Probabilidad y Estadística',
                'title' => 'Muestreo: error estándar y confianza en contenido de metal',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Probabilidad y Estadística: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's2_prob_est_c' => [
                'semester' => 2,
                'subject_slug' => 'prob_est',
                'subject_name' => 'Probabilidad y Estadística',
                'title' => 'Control de proceso: gráficos y alertas en planta (simulación)',
                'archetype' => 'math_mine',
                'profile' => [2, 5],
                'summary' => 'Actividad práctica para Probabilidad y Estadística: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C5). Escenario: math_mine.',
            ],
            's2_res_mat_a' => [
                'semester' => 2,
                'subject_slug' => 'res_mat',
                'subject_name' => 'Resistencia de Materiales',
                'title' => 'Pilar minero: esfuerzo admisible y factor de seguridad (caso guiado)',
                'archetype' => 'math_mine',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Resistencia de Materiales: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: math_mine.',
            ],
            's2_res_mat_b' => [
                'semester' => 2,
                'subject_slug' => 'res_mat',
                'subject_name' => 'Resistencia de Materiales',
                'title' => 'Viga de pasarela: flexión en estructura de acceso a galería',
                'archetype' => 'tunnel_3d',
                'profile' => [4],
                'summary' => 'Actividad práctica para Resistencia de Materiales: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: tunnel_3d.',
            ],
            's2_res_mat_c' => [
                'semester' => 2,
                'subject_slug' => 'res_mat',
                'subject_name' => 'Resistencia de Materiales',
                'title' => 'Estado de esfuerzos en roca: conceptual con Mohr simplificado',
                'archetype' => 'math_mine',
                'profile' => [4],
                'summary' => 'Actividad práctica para Resistencia de Materiales: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: math_mine.',
            ],
            's2_topo_min_a' => [
                'semester' => 2,
                'subject_slug' => 'topo_min',
                'subject_name' => 'Topografía de Minas',
                'title' => 'Polígono en superficie: compensación de ángulos en campamento minero',
                'archetype' => 'survey_field',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Topografía de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: survey_field.',
            ],
            's2_topo_min_b' => [
                'semester' => 2,
                'subject_slug' => 'topo_min',
                'subject_name' => 'Topografía de Minas',
                'title' => 'GNSS y coordenadas: paso UTM en borde de tajo',
                'archetype' => 'survey_field',
                'profile' => [4],
                'summary' => 'Actividad práctica para Topografía de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: survey_field.',
            ],
            's2_topo_min_c' => [
                'semester' => 2,
                'subject_slug' => 'topo_min',
                'subject_name' => 'Topografía de Minas',
                'title' => 'Replanteo de barreno: ángulo y azimut en malla de perforación',
                'archetype' => 'survey_field',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Topografía de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: survey_field.',
            ],
            's3_edo_a' => [
                'semester' => 3,
                'subject_slug' => 'edo',
                'subject_name' => 'Ecuaciones Diferenciales',
                'title' => 'Modelo de mezcla en estanque de proceso (EDO de primer orden)',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Ecuaciones Diferenciales: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's3_edo_b' => [
                'semester' => 3,
                'subject_slug' => 'edo',
                'subject_name' => 'Ecuaciones Diferenciales',
                'title' => 'Enfriamiento de equipo: ley de Newton aplicada a motor',
                'archetype' => 'math_mine',
                'profile' => [4],
                'summary' => 'Actividad práctica para Ecuaciones Diferenciales: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: math_mine.',
            ],
            's3_edo_c' => [
                'semester' => 3,
                'subject_slug' => 'edo',
                'subject_name' => 'Ecuaciones Diferenciales',
                'title' => 'Crecimiento de población de bacterias en lixiviación (logístico conceptual)',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Ecuaciones Diferenciales: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's3_mec_rocas_a' => [
                'semester' => 3,
                'subject_slug' => 'mec_rocas',
                'subject_name' => 'Elementos Mecánicos de Rocas',
                'title' => 'Arco de excavación: empuje de roca y sostenimiento en túnel 3D',
                'archetype' => 'tunnel_3d',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Elementos Mecánicos de Rocas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: tunnel_3d.',
            ],
            's3_mec_rocas_b' => [
                'semester' => 3,
                'subject_slug' => 'mec_rocas',
                'subject_name' => 'Elementos Mecánicos de Rocas',
                'title' => 'Pilares y estribos: dimensionamiento conceptual en cámara',
                'archetype' => 'tunnel_3d',
                'profile' => [4],
                'summary' => 'Actividad práctica para Elementos Mecánicos de Rocas: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: tunnel_3d.',
            ],
            's3_mec_rocas_c' => [
                'semester' => 3,
                'subject_slug' => 'mec_rocas',
                'subject_name' => 'Elementos Mecánicos de Rocas',
                'title' => 'Clasificación RMR aplicada a tramo de galería (flujo guiado)',
                'archetype' => 'math_mine',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Elementos Mecánicos de Rocas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: math_mine.',
            ],
            's3_mec_fluidos_a' => [
                'semester' => 3,
                'subject_slug' => 'mec_fluidos',
                'subject_name' => 'Mecánica de Fluidos y Termodinámica',
                'title' => 'Bernoulli en tubería de impulsión de agua de mina',
                'archetype' => 'math_mine',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Mecánica de Fluidos y Termodinámica: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: math_mine.',
            ],
            's3_mec_fluidos_b' => [
                'semester' => 3,
                'subject_slug' => 'mec_fluidos',
                'subject_name' => 'Mecánica de Fluidos y Termodinámica',
                'title' => 'Pérdidas en conducto: caudal y diámetro (ejercicio interactivo)',
                'archetype' => 'math_mine',
                'profile' => [4],
                'summary' => 'Actividad práctica para Mecánica de Fluidos y Termodinámica: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: math_mine.',
            ],
            's3_mec_fluidos_c' => [
                'semester' => 3,
                'subject_slug' => 'mec_fluidos',
                'subject_name' => 'Mecánica de Fluidos y Termodinámica',
                'title' => 'Ciclo termodinámico del aire comprimido en perforadoras (conceptual)',
                'archetype' => 'math_mine',
                'profile' => [4],
                'summary' => 'Actividad práctica para Mecánica de Fluidos y Termodinámica: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: math_mine.',
            ],
            's3_perf_tron_a' => [
                'semester' => 3,
                'subject_slug' => 'perf_tron',
                'subject_name' => 'Perforación y Tronadura',
                'title' => 'Frente de perforación: malla, burden y esquiva en túnel',
                'archetype' => 'drill_site',
                'profile' => [1, 3],
                'summary' => 'Actividad práctica para Perforación y Tronadura: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C3). Escenario: drill_site.',
            ],
            's3_perf_tron_b' => [
                'semester' => 3,
                'subject_slug' => 'perf_tron',
                'subject_name' => 'Perforación y Tronadura',
                'title' => 'Carga y secuencia de disparo: retardo y vibración',
                'archetype' => 'drill_site',
                'profile' => [1, 3],
                'summary' => 'Actividad práctica para Perforación y Tronadura: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C3). Escenario: drill_site.',
            ],
            's3_perf_tron_c' => [
                'semester' => 3,
                'subject_slug' => 'perf_tron',
                'subject_name' => 'Perforación y Tronadura',
                'title' => 'Seguridad en tronadura: perímetro de exclusión y señalización',
                'archetype' => 'safety_module',
                'profile' => [3, 5],
                'summary' => 'Actividad práctica para Perforación y Tronadura: vinculada al programa de asignatura y al perfil de egreso (competencias C3, C5). Escenario: safety_module.',
            ],
            's3_prosp_yac_a' => [
                'semester' => 3,
                'subject_slug' => 'prosp_yac',
                'subject_name' => 'Prospección y Evaluación de Yacimientos Mineros',
                'title' => 'Modelo de recurso: ley media y volumen en bloque 3D simplificado',
                'archetype' => 'pit_3d',
                'profile' => [1, 2, 4],
                'summary' => 'Actividad práctica para Prospección y Evaluación de Yacimientos Mineros: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2, C4). Escenario: pit_3d.',
            ],
            's3_prosp_yac_b' => [
                'semester' => 3,
                'subject_slug' => 'prosp_yac',
                'subject_name' => 'Prospección y Evaluación de Yacimientos Mineros',
                'title' => 'Geoestadística básica: variograma y kriging explicado paso a paso',
                'archetype' => 'math_mine',
                'profile' => [4],
                'summary' => 'Actividad práctica para Prospección y Evaluación de Yacimientos Mineros: vinculada al programa de asignatura y al perfil de egreso (competencias C4). Escenario: math_mine.',
            ],
            's3_prosp_yac_c' => [
                'semester' => 3,
                'subject_slug' => 'prosp_yac',
                'subject_name' => 'Prospección y Evaluación de Yacimientos Mineros',
                'title' => 'Cut-off y VAN preliminar: decisión de explotar o no el bloque',
                'archetype' => 'office_sim',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Prospección y Evaluación de Yacimientos Mineros: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: office_sim.',
            ],
            's3_exp_sub_a' => [
                'semester' => 3,
                'subject_slug' => 'exp_sub',
                'subject_name' => 'Sistema de Explotación Subterráneo',
                'title' => 'Secuencia de extracción: niveles, panel y relleno hidráulico (vista 3D)',
                'archetype' => 'tunnel_3d',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Sistema de Explotación Subterráneo: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: tunnel_3d.',
            ],
            's3_exp_sub_b' => [
                'semester' => 3,
                'subject_slug' => 'exp_sub',
                'subject_name' => 'Sistema de Explotación Subterráneo',
                'title' => 'Selección de método: cámara y pilar vs sublevel stoping (comparador)',
                'archetype' => 'tunnel_3d',
                'profile' => [1, 4],
                'summary' => 'Actividad práctica para Sistema de Explotación Subterráneo: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C4). Escenario: tunnel_3d.',
            ],
            's3_exp_sub_c' => [
                'semester' => 3,
                'subject_slug' => 'exp_sub',
                'subject_name' => 'Sistema de Explotación Subterráneo',
                'title' => 'Programación de producción: turnos y equipos en frente',
                'archetype' => 'office_sim',
                'profile' => [1, 2, 5],
                'summary' => 'Actividad práctica para Sistema de Explotación Subterráneo: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2, C5). Escenario: office_sim.',
            ],
            's4_diseno_proy_a' => [
                'semester' => 4,
                'subject_slug' => 'diseno_proy',
                'subject_name' => 'Diseño y Evaluación de Proyectos',
                'title' => 'Flujo de evaluación: mercado, técnico, legal y ambiental',
                'archetype' => 'office_sim',
                'profile' => [2, 4, 6],
                'summary' => 'Actividad práctica para Diseño y Evaluación de Proyectos: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4, C6). Escenario: office_sim.',
            ],
            's4_diseno_proy_b' => [
                'semester' => 4,
                'subject_slug' => 'diseno_proy',
                'subject_name' => 'Diseño y Evaluación de Proyectos',
                'title' => 'VAN, TIR y sensibilidad del precio del metal',
                'archetype' => 'office_sim',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Diseño y Evaluación de Proyectos: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: office_sim.',
            ],
            's4_diseno_proy_c' => [
                'semester' => 4,
                'subject_slug' => 'diseno_proy',
                'subject_name' => 'Diseño y Evaluación de Proyectos',
                'title' => 'Matriz FODA de proyecto minero ficticio',
                'archetype' => 'innovation_board',
                'profile' => [2, 5],
                'summary' => 'Actividad práctica para Diseño y Evaluación de Proyectos: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C5). Escenario: innovation_board.',
            ],
            's4_eco_gral_a' => [
                'semester' => 4,
                'subject_slug' => 'eco_gral',
                'subject_name' => 'Economía General',
                'title' => 'Oferta y demanda del cobre: equilibrio y shocks',
                'archetype' => 'office_sim',
                'profile' => [2, 6],
                'summary' => 'Actividad práctica para Economía General: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C6). Escenario: office_sim.',
            ],
            's4_eco_gral_b' => [
                'semester' => 4,
                'subject_slug' => 'eco_gral',
                'subject_name' => 'Economía General',
                'title' => 'Elasticidad e impacto en ingreso de la mina',
                'archetype' => 'math_mine',
                'profile' => [2],
                'summary' => 'Actividad práctica para Economía General: vinculada al programa de asignatura y al perfil de egreso (competencias C2). Escenario: math_mine.',
            ],
            's4_eco_gral_c' => [
                'semester' => 4,
                'subject_slug' => 'eco_gral',
                'subject_name' => 'Economía General',
                'title' => 'Costo de oportunidad: invertir en faena vs alternativa financiera',
                'archetype' => 'office_sim',
                'profile' => [2, 6],
                'summary' => 'Actividad práctica para Economía General: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C6). Escenario: office_sim.',
            ],
            's4_innov_tec_a' => [
                'semester' => 4,
                'subject_slug' => 'innov_tec',
                'subject_name' => 'Innovación y Tecnología',
                'title' => 'Mapa de I+D+i: desde idea a prototipo en minería',
                'archetype' => 'innovation_board',
                'profile' => [2, 4, 5],
                'summary' => 'Actividad práctica para Innovación y Tecnología: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4, C5). Escenario: innovation_board.',
            ],
            's4_innov_tec_b' => [
                'semester' => 4,
                'subject_slug' => 'innov_tec',
                'subject_name' => 'Innovación y Tecnología',
                'title' => 'Transferencia tecnológica y alianzas universidad–industria',
                'archetype' => 'innovation_board',
                'profile' => [2, 5],
                'summary' => 'Actividad práctica para Innovación y Tecnología: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C5). Escenario: innovation_board.',
            ],
            's4_innov_tec_c' => [
                'semester' => 4,
                'subject_slug' => 'innov_tec',
                'subject_name' => 'Innovación y Tecnología',
                'title' => 'Emprendimiento: pitch de producto para servicio minero',
                'archetype' => 'office_sim',
                'profile' => [2, 5, 6],
                'summary' => 'Actividad práctica para Innovación y Tecnología: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C5, C6). Escenario: office_sim.',
            ],
            's4_proc_metal_a' => [
                'semester' => 4,
                'subject_slug' => 'proc_metal',
                'subject_name' => 'Procesos Metalúrgicos',
                'title' => 'Flotación: reactivos y recuperación en celda (flujo animado)',
                'archetype' => 'flow_process',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Procesos Metalúrgicos: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: flow_process.',
            ],
            's4_proc_metal_b' => [
                'semester' => 4,
                'subject_slug' => 'proc_metal',
                'subject_name' => 'Procesos Metalúrgicos',
                'title' => 'Lixiviación: cinética y tiempo de residencia',
                'archetype' => 'flow_process',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Procesos Metalúrgicos: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: flow_process.',
            ],
            's4_proc_metal_c' => [
                'semester' => 4,
                'subject_slug' => 'proc_metal',
                'subject_name' => 'Procesos Metalúrgicos',
                'title' => 'Balance metalúrgico global: ley cabeza vs cola',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Procesos Metalúrgicos: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's4_exp_rajo_a' => [
                'semester' => 4,
                'subject_slug' => 'exp_rajo',
                'subject_name' => 'Sistema de Explotación a Rajo Abierto',
                'title' => 'Diseño de bancos, bermas y ancho de rampa en tajo 3D',
                'archetype' => 'pit_3d',
                'pit_scene' => 'design',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Sistema de Explotación a Rajo Abierto: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: pit_3d.',
            ],
            's4_exp_rajo_b' => [
                'semester' => 4,
                'subject_slug' => 'exp_rajo',
                'subject_name' => 'Sistema de Explotación a Rajo Abierto',
                'title' => 'Secuencia de fases y botadero interno',
                'archetype' => 'pit_3d',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Sistema de Explotación a Rajo Abierto: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: pit_3d.',
            ],
            's4_exp_rajo_c' => [
                'semester' => 4,
                'subject_slug' => 'exp_rajo',
                'subject_name' => 'Sistema de Explotación a Rajo Abierto',
                'title' => 'Estabilidad de talud: factores y monitoreo superficial',
                'archetype' => 'pit_3d',
                'profile' => [2, 3],
                'summary' => 'Actividad práctica para Sistema de Explotación a Rajo Abierto: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C3). Escenario: pit_3d.',
            ],
            's4_vent_mina_a' => [
                'semester' => 4,
                'subject_slug' => 'vent_mina',
                'subject_name' => 'Ventilación de Minas',
                'title' => 'Red de conductos: pérdidas y ventilador principal (modelo conceptual)',
                'archetype' => 'vent_shaft',
                'profile' => [1, 3, 4],
                'summary' => 'Actividad práctica para Ventilación de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C3, C4). Escenario: vent_shaft.',
            ],
            's4_vent_mina_b' => [
                'semester' => 4,
                'subject_slug' => 'vent_mina',
                'subject_name' => 'Ventilación de Minas',
                'title' => 'Gases, polvo y control en frente de trabajo',
                'archetype' => 'vent_shaft',
                'profile' => [3],
                'summary' => 'Actividad práctica para Ventilación de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C3). Escenario: vent_shaft.',
            ],
            's4_vent_mina_c' => [
                'semester' => 4,
                'subject_slug' => 'vent_mina',
                'subject_name' => 'Ventilación de Minas',
                'title' => 'Costo energético del ventilador: decisión de caudal óptimo',
                'archetype' => 'math_mine',
                'profile' => [2, 4],
                'summary' => 'Actividad práctica para Ventilación de Minas: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4). Escenario: math_mine.',
            ],
            's5_dir_emp_a' => [
                'semester' => 5,
                'subject_slug' => 'dir_emp',
                'subject_name' => 'Dirección y Gestión de Empresas',
                'title' => 'Funciones de administración aplicadas a faena minera',
                'archetype' => 'office_sim',
                'profile' => [1, 5, 6],
                'summary' => 'Actividad práctica para Dirección y Gestión de Empresas: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C5, C6). Escenario: office_sim.',
            ],
            's5_dir_emp_b' => [
                'semester' => 5,
                'subject_slug' => 'dir_emp',
                'subject_name' => 'Dirección y Gestión de Empresas',
                'title' => 'Cultura organizacional y seguridad como valor',
                'archetype' => 'office_sim',
                'profile' => [5, 6],
                'summary' => 'Actividad práctica para Dirección y Gestión de Empresas: vinculada al programa de asignatura y al perfil de egreso (competencias C5, C6). Escenario: office_sim.',
            ],
            's5_dir_emp_c' => [
                'semester' => 5,
                'subject_slug' => 'dir_emp',
                'subject_name' => 'Dirección y Gestión de Empresas',
                'title' => 'RSC y actores: comunidad, Estado y empresa',
                'archetype' => 'office_sim',
                'profile' => [2, 6],
                'summary' => 'Actividad práctica para Dirección y Gestión de Empresas: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C6). Escenario: office_sim.',
            ],
            's5_proy_min_a' => [
                'semester' => 5,
                'subject_slug' => 'proy_min',
                'subject_name' => 'Proyecto Minero',
                'title' => 'Integración 3D: yacimiento–mina–planta–cierre (recorrido)',
                'archetype' => 'pit_3d',
                'profile' => [1, 2, 4],
                'summary' => 'Actividad práctica para Proyecto Minero: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2, C4). Escenario: pit_3d.',
            ],
            's5_proy_min_b' => [
                'semester' => 5,
                'subject_slug' => 'proy_min',
                'subject_name' => 'Proyecto Minero',
                'title' => 'Cronograma y dependencias del proyecto de inversión',
                'archetype' => 'office_sim',
                'profile' => [2, 4, 5],
                'summary' => 'Actividad práctica para Proyecto Minero: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C4, C5). Escenario: office_sim.',
            ],
            's5_proy_min_c' => [
                'semester' => 5,
                'subject_slug' => 'proy_min',
                'subject_name' => 'Proyecto Minero',
                'title' => 'Evaluación ambiental y social en ciclo de vida',
                'archetype' => 'office_sim',
                'profile' => [2, 6],
                'summary' => 'Actividad práctica para Proyecto Minero: vinculada al programa de asignatura y al perfil de egreso (competencias C2, C6). Escenario: office_sim.',
            ],
            's5_proy_tit_a' => [
                'semester' => 5,
                'subject_slug' => 'proy_tit',
                'subject_name' => 'Proyecto de Título',
                'title' => 'Diseño de pregunta de investigación aplicada a minería',
                'archetype' => 'thesis_lab',
                'profile' => [4, 5, 6],
                'summary' => 'Actividad práctica para Proyecto de Título: vinculada al programa de asignatura y al perfil de egreso (competencias C4, C5, C6). Escenario: thesis_lab.',
            ],
            's5_proy_tit_b' => [
                'semester' => 5,
                'subject_slug' => 'proy_tit',
                'subject_name' => 'Proyecto de Título',
                'title' => 'Metodología: fuentes, datos y ética del estudio',
                'archetype' => 'thesis_lab',
                'profile' => [5, 6],
                'summary' => 'Actividad práctica para Proyecto de Título: vinculada al programa de asignatura y al perfil de egreso (competencias C5, C6). Escenario: thesis_lab.',
            ],
            's5_proy_tit_c' => [
                'semester' => 5,
                'subject_slug' => 'proy_tit',
                'subject_name' => 'Proyecto de Título',
                'title' => 'Comunicación científica: estructura del informe final',
                'archetype' => 'thesis_lab',
                'profile' => [5, 6],
                'summary' => 'Actividad práctica para Proyecto de Título: vinculada al programa de asignatura y al perfil de egreso (competencias C5, C6). Escenario: thesis_lab.',
            ],
            's5_serv_min_a' => [
                'semester' => 5,
                'subject_slug' => 'serv_min',
                'subject_name' => 'Servicios Mineros',
                'title' => 'Red de agua interior mina: bombas y estaciones',
                'archetype' => 'tunnel_3d',
                'profile' => [1, 2],
                'summary' => 'Actividad práctica para Servicios Mineros: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2). Escenario: tunnel_3d.',
            ],
            's5_serv_min_b' => [
                'semester' => 5,
                'subject_slug' => 'serv_min',
                'subject_name' => 'Servicios Mineros',
                'title' => 'Subestación eléctrica: transformación y normativa Sernageomin',
                'archetype' => 'safety_module',
                'profile' => [3, 4],
                'summary' => 'Actividad práctica para Servicios Mineros: vinculada al programa de asignatura y al perfil de egreso (competencias C3, C4). Escenario: safety_module.',
            ],
            's5_serv_min_c' => [
                'semester' => 5,
                'subject_slug' => 'serv_min',
                'subject_name' => 'Servicios Mineros',
                'title' => 'Mantenimiento e inventario crítico de repuestos',
                'archetype' => 'office_sim',
                'profile' => [1, 2, 5],
                'summary' => 'Actividad práctica para Servicios Mineros: vinculada al programa de asignatura y al perfil de egreso (competencias C1, C2, C5). Escenario: office_sim.',
            ],
        ];
    }
}
